# Generated by Django 6.0.4 on 2026-04-15 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveIntegerField()),
                ('part', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'chapter_number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('accent_color', models.CharField(default='#0a84ff', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.TextField()),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='', max_length=10)),
                ('tldr', models.TextField(blank=True, default='')),
                ('answer', models.TextField(blank=True, default='')),
                ('points', models.JSONField(blank=True, default=list)),
                ('diagram', models.TextField(blank=True, default='')),
                ('diagram_caption', models.CharField(blank=True, default='', max_length=300)),
                ('diagram2', models.TextField(blank=True, default='')),
                ('diagram2_caption', models.CharField(blank=True, default='', max_length=300)),
                ('table_data', models.JSONField(blank=True, null=True)),
                ('followup', models.TextField(blank=True, default='')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='chapters.chapter')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='chapters.subject'),
        ),
        migrations.CreateModel(
            name='Takeaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takeaways', to='chapters.chapter')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('subject', 'chapter_number')},
        ),
    ]
