# Generated by Django 6.0.4 on 2026-04-15 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0004_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('keywords', models.JSONField(default=list)),
                ('source', models.CharField(choices=[('chapter', 'From Chapter'), ('web', 'Web Search'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_topics', to='chapters.chapter')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_topics', to='chapters.subject')),
            ],
            options={
                'ordering': ['subject', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('questions_json', models.JSONField(default=dict)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_history', to='chapters.subscription')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_history', to='chapters.emailtopic')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('subscription', 'topic')},
            },
        ),
    ]
