# Generated by Django 6.0.4 on 2026-04-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0005_email_topic_and_sent_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagedrequest',
            name='target_model',
            field=models.CharField(choices=[('subject', 'Subject'), ('chapter', 'Chapter'), ('question', 'Question'), ('takeaway', 'Takeaway'), ('chapter_populate', 'Chapter Populate')], max_length=20),
        ),
    ]
